import * as XLSX from "xlsx";

const PLACEHOLDER = "[placeholder]";
const CENTRIC_ID = "";

export const CENTRIC_EXPORT_SHEET_NAMES = [
  "Glossary",
  "Brand",
  "Menus",
  "Categories",
  "Items",
  "Modifier Groups",
  "Modifiers",
  "Relationships",
];

const BRAND_HEADERS = ["id", "name", "description", "is_active", "is_simplified_view", "frictionless_partner"];
const MENU_HEADERS = ["id", "name", "sequence", "name-fr", "name-es", "name-kvi"];
const CATEGORY_HEADERS = ["id", "name", "label", "is_active", "sequence", "name-fr", "name-es", "name-kvi"];
const ITEM_BASE_HEADERS = [
  "id",
  "unique_id",
  "posid",
  "name",
  "label",
  "name_on_kds",
  "name_on_receipt",
  "name_on_pos",
  "description",
  "price",
  "calories",
  "cost",
  "is_active",
  "barcode",
  "tags",
  "line_route",
  "reporting_category_primary",
  "reporting_category_secondary",
  "weight_unit",
  "weight_amount",
  "meal_value",
  "is_featured",
  "tax_tags",
  "tax_jwo_code",
  "tax_tag_code",
  "mrn",
  "name-fr",
  "name-es",
  "name-kvi",
  "description-fr",
  "description-es",
  "description-kvi",
];
const MODIFIER_BASE_HEADERS = [
  "id",
  "posid",
  "unique_id",
  "name",
  "label",
  "name_on_receipt",
  "name_on_kds",
  "name_on_pos",
  "description",
  "price",
  "calories",
  "cost",
  "is_active",
  "barcode",
  "tags",
  "line_route",
  "reporting_category_primary",
  "reporting_category_secondary",
  "weight_unit",
  "weight_amount",
  "price_for_none",
  "price_for_less",
  "price_for_more",
  "pre_surcharge",
  "post_surcharge",
  "tax_tags",
  "tax_tag_code",
  "mrn",
  "name-fr",
  "name-es",
  "name-kvi",
  "description-fr",
  "description-es",
  "description-kvi",
];
const MODIFIER_GROUP_HEADERS = ["id", "name", "label", "description", "is_active", "min", "max", "order_type", "limit", "sizing", "is_incremental", "name-fr", "name-es", "name-kvi"];
const RELATIONSHIP_HEADERS = ["Record Type", "Record Name", "Parent Name", "Record ID", "Parent ID", "Sequence"];

function cleanText(value) {
  return String(value ?? "").trim();
}

function requiredText(value) {
  return cleanText(value) || PLACEHOLDER;
}

function centricName(value) {
  return requiredText(value).toUpperCase();
}

function priceText(value) {
  const text = cleanText(value);
  if (!text) return PLACEHOLDER;
  return text.replace(/^\$/, "").replace(/,/g, "");
}

function areaHeaders(areaOrder = []) {
  return areaOrder.map((area) => `$$${area}`);
}

function areaValues(areaOrder = [], areaPrices = {}, fallback = "") {
  return areaOrder.map((area) => priceText(areaPrices?.[area] || (area === "SEA" ? fallback : "")));
}

function relatedModifierGroups(item, modifierGroups = []) {
  const itemGroupNames = item?.modifierGroups || [];
  return modifierGroups.filter((group) => itemGroupNames.some((name) => {
    const left = cleanText(group.name).toLowerCase();
    const right = cleanText(name).toLowerCase();
    return left && right && (left.includes(right) || right.includes(left));
  }));
}

function itemExportName(item = {}) {
  const name = cleanText(item.name);
  const label = cleanText(item.label);
  if (!name || /^new item$/i.test(name)) return requiredText(label);
  return name;
}

function uniqueByName(rows = []) {
  const seen = new Set();
  return rows.filter((row) => {
    const key = cleanText(row.name).toLowerCase();
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function selectedRowsWithCategories(selectedMenu = {}) {
  const rows = [];
  let activeCategory = "";
  (selectedMenu.items || []).forEach((item, index) => {
    if (item.recordType === "divider") {
      activeCategory = centricName(item.title || "Items");
      return;
    }
    rows.push({
      item,
      index,
      categoryName: activeCategory || centricName(item.category || "Items"),
    });
  });
  return rows;
}

function buildGlossaryRows() {
  return [
    ["This file is an import/export format for managing Menu data in CentricOS."],
    ["Generated by Culinary Tools SSMT from app-side menu, pricing, and modifier records."],
    ["Centric-owned IDs are intentionally left blank; unknown optional business properties use [placeholder]."],
    ["Validate placeholder fields with IT before importing into Centric."],
  ];
}

function appendSheet(workbook, name, rows) {
  const sheet = XLSX.utils.aoa_to_sheet(rows);
  XLSX.utils.book_append_sheet(workbook, sheet, name);
}

export function centricExportFileName(brandName) {
  const name = cleanText(brandName);
  return name ? `${name} SSMT Export.xlsx` : "SSMT Export.xlsx";
}

export function buildCentricExportWorkbook({ selectedMenu = {}, areaOrder = [], modifierGroups = [] } = {}) {
  const workbook = XLSX.utils.book_new();
  const brandName = requiredText(selectedMenu.name);
  const menuName = centricName(selectedMenu.name);
  const itemRowsWithCategories = selectedRowsWithCategories(selectedMenu);
  const categories = [...new Set(itemRowsWithCategories.map(({ categoryName }) => categoryName))];
  const usedModifierGroups = uniqueByName(itemRowsWithCategories.flatMap(({ item }) => relatedModifierGroups(item, modifierGroups)));
  const itemHeaders = [...ITEM_BASE_HEADERS, ...areaHeaders(areaOrder)];
  const modifierHeaders = [...MODIFIER_BASE_HEADERS, ...areaHeaders(areaOrder)];

  appendSheet(workbook, "Glossary", buildGlossaryRows());
  appendSheet(workbook, "Brand", [
    BRAND_HEADERS,
    [CENTRIC_ID, brandName, PLACEHOLDER, "TRUE", PLACEHOLDER, PLACEHOLDER],
  ]);
  appendSheet(workbook, "Menus", [
    MENU_HEADERS,
    [CENTRIC_ID, menuName, "", "", "", ""],
  ]);
  appendSheet(workbook, "Categories", [
    CATEGORY_HEADERS,
    ...categories.map((name, index) => [CENTRIC_ID, name, "", "TRUE", String(index + 1), "", "", ""]),
  ]);
  appendSheet(workbook, "Items", [
    itemHeaders,
    ...itemRowsWithCategories.map(({ item, categoryName }) => {
      const name = itemExportName(item);
      const label = requiredText(item.label || item.name);
      return [
        CENTRIC_ID,
        CENTRIC_ID,
        CENTRIC_ID,
        name,
        label,
        label,
        label,
        label,
        requiredText(item.description),
        priceText(item.seaPrice || item.price),
        requiredText(item.calories),
        PLACEHOLDER,
        "TRUE",
        "",
        "",
        "",
        requiredText(item.category || "Food"),
        requiredText(item.secondaryCategory || item.reportingCategorySecondary),
        "",
        "",
        "",
        "FALSE",
        "",
        "",
        "",
        cleanText(item.mrn),
        "",
        "",
        "",
        "",
        "",
        "",
        ...areaValues(areaOrder, item.areaPrices, item.seaPrice || item.price),
      ];
    }),
  ]);
  appendSheet(workbook, "Modifier Groups", [
    MODIFIER_GROUP_HEADERS,
    ...usedModifierGroups.map((group) => [
      CENTRIC_ID,
      requiredText(group.name),
      "",
      PLACEHOLDER,
      "TRUE",
      cleanText(group.minQty) || "0",
      cleanText(group.maxQty) || "",
      "selection",
      "",
      "",
      "FALSE",
      "",
      "",
      "",
    ]),
  ]);
  appendSheet(workbook, "Modifiers", [
    modifierHeaders,
    ...usedModifierGroups.flatMap((group) => (group.choices || []).map((choice) => {
      const name = requiredText(choice.label || choice.name);
      return [
        CENTRIC_ID,
        CENTRIC_ID,
        CENTRIC_ID,
        name,
        name,
        name,
        name,
        name,
        requiredText(choice.description),
        priceText(choice.price || choice.priceSelector),
        requiredText(choice.calories),
        PLACEHOLDER,
        "TRUE",
        "",
        "",
        "",
        "Food",
        "Modifier",
        "",
        "",
        "0",
        "0",
        "0",
        priceText(choice.price || choice.priceSelector),
        priceText(choice.price || choice.priceSelector),
        "",
        "",
        cleanText(choice.mrn),
        "",
        "",
        "",
        "",
        "",
        "",
        ...areaValues(areaOrder, choice.areaPrices, choice.price || choice.priceSelector),
      ];
    })),
  ]);
  appendSheet(workbook, "Relationships", [
    RELATIONSHIP_HEADERS,
    ["Menu", menuName, brandName, CENTRIC_ID, CENTRIC_ID, ""],
    ...categories.map((name, index) => ["Category", name, menuName, CENTRIC_ID, CENTRIC_ID, String(index)]),
    ...itemRowsWithCategories.map(({ item, categoryName }, index) => ["Item", itemExportName(item), categoryName, CENTRIC_ID, CENTRIC_ID, String(index)]),
    ...itemRowsWithCategories.flatMap(({ item }) => relatedModifierGroups(item, usedModifierGroups).map((group, index) => ["Modifier Group", requiredText(group.name), itemExportName(item), CENTRIC_ID, CENTRIC_ID, String(index)])),
    ...usedModifierGroups.flatMap((group) => (group.choices || []).map((choice, index) => ["Modifier", requiredText(choice.label || choice.name), requiredText(group.name), CENTRIC_ID, CENTRIC_ID, String(index)])),
  ]);

  return workbook;
}

export function downloadCentricExport({ selectedMenu, areaOrder, modifierGroups }) {
  const workbook = buildCentricExportWorkbook({ selectedMenu, areaOrder, modifierGroups });
  XLSX.writeFile(workbook, centricExportFileName(selectedMenu?.name));
}
