// Smartsheet database contract. Keep these labels exactly matched to the master database column names.
export const SMARTSHEET_DATABASE_STORAGE_KEY = "culinaryToolsSmartsheetReadyRecords_v1";
export const NEIGHBORHOOD_ROTATIONS_STORAGE_KEY = "neighborhoodRotations_v6_databaseAligned";

export const SMARTSHEET_COLUMNS = Object.freeze({
  recordId: "Record ID",
  parentRecordId: "Parent Record ID",
  recordType: "Record Type",
  status: "Status",
  district: "District",
  cafeUnit: "Café / Unit",
  weekStartDate: "Week Start Date",
  weekEndDate: "Week End Date",
  businessDate: "Business Date",
  dayOfWeek: "Day of Week",
  dateRangeLabel: "Date Range Label",
  station: "Station",
  stationDisplayName: "Station Display Name",
  stationKey: "Station Key",
  stationSortOrder: "Station Sort Order",
  slotNumber: "Slot Number",
  menuConcept: "Menu / Concept",
  stationSubConcept: "Station / Sub-Concept",
  menuBlockLabel: "Menu Block Label",
  menuBlockType: "Menu Block Type",
  globalBlockId: "Global Block ID",
  globalBlockIndex: "Global Block Index",
  globalBlockDays: "Global Block Days",
  isReadOnly: "Is Read Only",
  startedPreviousWeek: "Started Previous Week",
  continuesNextWeek: "Continues Next Week",
  nextWeekCarryoverDays: "Next Week Carryover Days",
  cycleSourceWeekStartDate: "Cycle Source Week Start Date",
  cycleSourceCafeUnit: "Cycle Source Café / Unit",
  cycleSourceRecordId: "Cycle Source Record ID",
  copiedFromCafeUnit: "Copied From Café / Unit",
  copiedFromRecordId: "Copied From Record ID",
  allowedOverlapGroup: "Allowed Overlap Group",
  promotionOverrideEnabled: "Promotion Override Enabled",
  promotionName: "Promotion Name",
  promotionDays: "Promotion Days",
  promotionStartDate: "Promotion Start Date",
  promotionEndDate: "Promotion End Date",
  returnToCycleDays: "Return To Cycle Days",
  returnToCycleStartDate: "Return To Cycle Start Date",
  returnToCycleEndDate: "Return To Cycle End Date",
  breaksNormalCycle: "Breaks Normal Cycle",
  cycleRecoveryNotes: "Cycle Recovery Notes",
  selectionType: "Selection Type",
  menuItemSelection: "Menu Item / Selection",
  mrn: "MRN",
  portion: "Portion",
  menuItemSortOrder: "Menu Item Sort Order",
  price: "Price",
  trueCost: "True Cost",
  foodCostPct: "Food Cost %",
  costRangeLow: "Cost Range Low",
  costRangeHigh: "Cost Range High",
  foodCostRangeLowPct: "Food Cost Range Low %",
  foodCostRangeHighPct: "Food Cost Range High %",
  enticingDescription: "Enticing Description",
  dietTags: "Diet Tags",
  allergens: "Allergens",
  uploadedSourceFileName: "Uploaded Source File Name",
  uploadedReportType: "Uploaded Report Type",
  detectedCafe: "Detected Café",
  detectedStation: "Detected Station",
  detectedDateRange: "Detected Date Range",
  sourceStationName: "Source Station Name",
  mappedStationKey: "Mapped Station Key",
  stationMappingNotes: "Station Mapping Notes",
  uploadedItemName: "Uploaded Item Name",
  matchedMenuWorksItem: "Matched MenuWorks Item",
  matchedMrn: "Matched MRN",
  matchConfidence: "Match Confidence",
  unmatchedItems: "Unmatched Items",
  uploadApplied: "Upload Applied",
  submittedBy: "Submitted By",
  submittedAt: "Submitted At",
  updatedBy: "Updated By",
  updatedAt: "Updated At",
  approvedBy: "Approved By",
  approvedAt: "Approved At",
  notes: "Notes",
  internalReviewNotes: "Internal Review Notes",
  alertType: "Alert Type",
  alertMessage: "Alert Message",
  alertSeverity: "Alert Severity",
  alertRecipients: "Alert Recipients",
  alertSent: "Alert Sent",
  alertSentAt: "Alert Sent At",
  alertResolved: "Alert Resolved",
  alertResolutionNotes: "Alert Resolution Notes",
  savedEntryCount: "Saved Entry Count",
  submittedEntryCount: "Submitted Entry Count",
  draftEntryCount: "Draft Entry Count",
  projectedFoodCostPct: "Projected Food Cost %",
  projectedTrueCostLow: "Projected True Cost Low",
  projectedTrueCostHigh: "Projected True Cost High",
  mostUsedMenuFlag: "Most Used Menu Flag",
  historyInclude: "History Include",
  ladleTotalTasks: "Ladle Total Tasks",
  ladleCompletedTasks: "Ladle Completed Tasks",
  ladleMissedTasks: "Ladle Missed Tasks",
  ladleCompliancePct: "Ladle Compliance %",
  ladleTargetPct: "Ladle Target %",
  ladleStatus: "Ladle Status",
  ladleTrend: "Ladle Trend",
  ladlePreviousCompliancePct: "Ladle Previous Compliance %",
  ladleVariancePct: "Ladle Variance %",
  ladleFocusArea: "Ladle Focus Area",
  ladleFollowUpNeeded: "Ladle Follow-Up Needed",
  ladleFollowUpOwner: "Ladle Follow-Up Owner",
  ladleFollowUpNotes: "Ladle Follow-Up Notes",
});

export const SMARTSHEET_RECORD_TYPES = Object.freeze({
  rotationHeader: "Rotation Header",
  globalBlock: "Global Block",
  globalSelection: "Global Selection",
  stationSelection: "Station Selection",
  grillSelection: "Grill Selection",
  carverySelection: "Carvery Selection",
  wokSelection: "Wok Selection",
  weekAtGlanceUpload: "Week at a Glance Upload",
  uploadedItem: "Uploaded Item",
  alertNotification: "Alert / Notification",
  ladleCompliance: "Ladle Compliance",
  menuWorksItem: "MenuWorks Item",
  menuEngineeringScenario: "Menu Engineering Scenario",
});

export const SMARTSHEET_SELECTION_TYPES = Object.freeze({
  entree: "Entrée",
  side: "Side",
  subRecipe: "Sub Recipe",
  extension: "Extension",
  lto: "LTO",
  regionalSpecial: "Regional Special",
  locationSpotlight: "Location Spotlight",
  carveryProtein: "Carvery Protein",
  carveryVegetable: "Carvery Vegetable",
  carveryStarch: "Carvery Starch",
  carveryHotSide: "Carvery Hot Side",
  carveryColdSide: "Carvery Cold Side",
  wokEntree: "Wok Entrée",
  wokSide: "Wok Side",
  wokBase: "Wok Base",
  wokSubRecipe: "Wok Sub Recipe",
  complianceMetric: "Compliance Metric",
});

export const STATION_SMARTSHEET_LABELS = Object.freeze({
  global: "Global",
  wok: "Wok",
  grill: "Grill",
  carvery: "Carvery",
  salad: "Salad",
  pizza: "Pizza",
  deli: "Deli",
  fishMarket: "Fish Market",
  freshFive: "Fresh Five",
  soup: "Soup",
  ladle: "Ladle",
});

export const REQUIRED_SMARTSHEET_COLUMNS_FOR_CURRENT_BUILD = Object.freeze(Object.values(SMARTSHEET_COLUMNS));


